# This is a basic workflow to help you get started with Actions

name: Update Flasher

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Update
        run: |
          rm *.bin
          wget https://github.com/ManCloud/GBAHD-Shield/releases/download/latest/gbaHD-esp32-bootloader.bin
          wget https://github.com/ManCloud/GBAHD-Shield/releases/download/latest/gbaHD-esp32.bin
          wget https://github.com/ManCloud/GBAHD-Shield/releases/download/latest/gbaHD-spiffs.bin
          wget https://github.com/ManCloud/GBAHD-Shield/releases/download/latest/gbaHD-partition-table.bin
          
      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192
        uses: EndBug/add-and-commit@v9.0.0
